[package]
name = "prom-remote-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.6"
snap = "1.1.0"
tokio = { version = "1.24.1", features = ["full"] }
warp = "0.3.2"

[build-dependencies]
prost-build = { version = "0.11.6" }
